# Generated by Django 3.1.2 on 2021-02-18 05:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210217_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question_type', models.PositiveSmallIntegerField(choices=[(1, 'Boolean'), (2, 'Only one answer is correct'), (3, 'More than one answer is correct'), (3, 'More than one answer is correct and all of them must be answered correctly')], default=1, verbose_name='Rol')),
                ('posible_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=5)),
                ('bool_answer', models.BooleanField(blank=True, null=True)),
                ('one_answer', models.CharField(max_length=200)),
                ('multiple_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=5)),
                ('score', models.IntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
        ),
    ]
