# Generated by Django 3.1.2 on 2021-02-18 05:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='multiple_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='one_answer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
