# Generated by Django 3.1.2 on 2021-02-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_questionuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Boolean'), (2, 'Only one answer is correct'), (3, 'More than one answer is correct'), (4, 'More than one answer is correct and all of them must be answered correctly')], default=1, verbose_name='Type Question'),
        ),
    ]
