# Generated by Django 3.1.2 on 2021-02-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210218_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='one_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
